import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 text-white px-6 py-4 flex justify-between items-center">
          <div className="flex items-center space-x-6">
            <a href="/" className="font-semibold hover:underline">
              Home
            </a>
            <a href="/my-tickets" className="font-semibold hover:underline">
              My Tickets
            </a>
            <a href="/wallet" className="font-semibold hover:underline">
              Wallet
            </a>
            <a href="/results" className="font-semibold hover:underline">
              Results
            </a>
            <a href="/profile" className="font-semibold hover:underline">
              Profile
            </a>
          </div>
          <div className="flex items-center space-x-4">
            <span className="text-sm">$2,400</span>
            <span className="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center text-xs">
              JD
            </span>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
